name: Check minecraft commands
author: Valentin Berlier <berlier.v@gmail.com>
description: Github action to validate minecraft data packs and function files.

branding:
  icon: check-square
  color: red

inputs:
  version:
    description: The version of mecha to install
    required: true
    default: 'latest'
  source:
    description: The list of data packs, functions files or folders to validate
    required: true
  minecraft:
    description: The version of minecraft to use for checking commands
    required: true
    default: '1.17'
  stats:
    description: Whether to output statistics
    required: true
    default: "false"
  log:
    description: The output log level
    required: true
    default: 'WARNING'

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Setup cache
      id: cached-mecha-venv
      uses: actions/cache@v2
      with:
        path: ~/.mecha_venv
        key: mecha-venv-${{ runner.os }}-${{ inputs.version }}
    - name: Run mecha
      env:
        CACHE_HIT: ${{ steps.cached-mecha-venv.outputs.cache-hit }}
        MECHA_VERSION: ${{ inputs.version }}
        MECHA_SOURCE: ${{ inputs.source }}
        MECHA_MINECRAFT: ${{ inputs.minecraft }}
        MECHA_STATS: ${{ inputs.stats == 'true' && '--stats' || '' }}
        MECHA_LOG: ${{ inputs.log }}
      run: |
        if [ "$CACHE_HIT" != "true" ] || [ ! -f ~/.mecha_venv/bin/python ]; then
          rm -rf ~/.mecha_venv
          python -m venv ~/.mecha_venv

          source ~/.mecha_venv/bin/activate

          if [ "$MECHA_VERSION" == "latest" ]; then
            pip install mecha
          else
            pip install "mecha==$MECHA_VERSION"
          fi
        else
          source ~/.mecha_venv/bin/activate
        fi

        shopt -s extglob
        mecha $MECHA_SOURCE --minecraft "$MECHA_MINECRAFT" --log "$MECHA_LOG" $MECHA_STATS
      shell: bash
